### ISSUE TITLE
questions about example NeXus file

### ISSUE THREAD

**Issue by prjemian** [lightsources/BES-XPCS-Pilot#13]
Questions were raised at the 2020-10-09 meeting

* No rois in XPCS in APS example datasets → Is there a “full example” available?
* CHX example has a different structure → converter needed:
    ['avg_img', 'bad_frame_list', 'g12b', 'g2', 'g2_fit_paras', 'g2b', 'g2b_fit_paras', 'imgsum', 'iq_saxs', 'iqst', 'mask', 'md', 'mean_int_sets', 'pixel_mask', 'q_saxs', 'qt', 'qval_dict', 'roi_mask', 'taus', 'tausb', 'times_roi']
* CXS np file have different structure → converter needed
* SAXS/I and SAXS/Q are separate entries to we want that merged (in XPCS)
* Who is responsible for the conversion of xy file format to the NXxpcs?

**Comment by ambarb** [comment]
we answered these questions in the hackathon.  we think this can be closed.
