### ISSUE TITLE
Scattering geometry nexus fields

### ISSUE THREAD

**Issue by dylanmcreynolds** [lightsources/BES-XPCS-Pilot#28]
-  `/entry/XPCS/instrument/mask/annotation/geometry`
-  `/entry/XPCS/instrument/mask/mask`
-  `/entry/XPCS/instrument/mask/dqmap`
-  `/entry/XPCS/instrument/mask/dqlist`
-  `/entry/XPCS/instrument/mask/dphilist`
-  `/entry/XPCS/instrument/mask/sqmap`

Except for /mask/mask, are these really masks?
Are these really instruments values?

**Comment by ambarb** [comment]
@dylanmcreynolds is this still relevant or should we close it?

For now we are relying on analysis code to provide Q information.

**Comment by dylanmcreynolds** [comment]
I think this has long been  superseded by your work. I'll go ahead an close it.
