### ISSUE TITLE
Want to have a NeXus units type of NX_ARBITRARY_UNITS

### ISSUE THREAD

**Issue by prjemian** [lightsources/BES-XPCS-Pilot#37]
Note that we want to have a NeXus units type of [`NX_ARBITRARY_UNITS`](https://github.com/nexusformat/definitions/issues/921).

_Originally posted by @prjemian in https://github.com/lightsources/BES-XPCS-Pilot/issues/35#issuecomment-830230346_

**Comment by ambarb** [comment]
This is assumed by our work that this is the case.  #35 is issue that addressed this and has PR associated. 

https://github.com/nexusformat/definitions/issues/921 

So we can close this for now.
