### ISSUE TITLE
one-time g2 for NeXus definition description online

### ISSUE THREAD

**Issue by ambarb** [lightsources/BES-XPCS-Pilot#45]
- [x] include Lumma Rev Sci Instrum 2000 Equation 1 ripresentino
- [x] formal name in documentation: "normalized intensity autocorrelation function"
- [x] long name attribute "normalized intensity autocorrelation function"
- [x] units: arbitrary units
- [x] plain text representation: `g2`

May as well add numerator of `g2`, which is G2 or `G2_unnormalized` see https://github.com/lightsources/BES-XPCS-Pilot/issues/46

**Comment by ambarb** [comment]
looks like this is related to #37 , once this is done, we can then finish this issue.

**Comment by ambarb** [comment]
@prjemian will make sure `NX_ANY` is replaced by `NX_ARBITRARY_UNITS`

**Comment by prjemian** [comment]
Looking at the use of `NX_ANY` (in this branch):

```bash
(base) prjemian@zap:~/.../xpcs/NeXus$ grep NX_ANY NXxpcs.nxdl.xml 
      <field name="g2" type="NX_NUMBER" units="NX_ANY" minOccurs="0" maxOccurs="1">
      <field name="g2_stderr" type="NX_NUMBER" units="NX_ANY" minOccurs="0" maxOccurs="1">
      <field name="G2_unnormalized" type="NX_NUMBER" units="NX_ANY" minOccurs="0" maxOccurs="1">
      <field name="two_time_corr_func" type="NX_NUMBER" units="NX_ANY" minOccurs="0" maxOccurs="1">
      <field name="g2_from_two_time_corr_func" type="NX_NUMBER" units="NX_ANY" minOccurs="0" maxOccurs="1">
      <field name="g2_from_two_time_corr_func_partials" type="NX_NUMBER" units="NX_ANY" minOccurs="0" maxOccurs="1">
```

will change units of all fields that start with `g2` (or `G2`).
