### ISSUE TITLE
replace tau with more universally accepted name

### ISSUE THREAD

**Issue by ambarb** [lightsources/BES-XPCS-Pilot#47]
to be updated next week....

**Comment by prjemian** [comment]
sneak peek from today's discussion: 
![clip1](https://user-images.githubusercontent.com/2279984/120845999-2c2dbc00-c537-11eb-8ee5-47bfaa2a470c.png)

**Comment by JulReinhardt** [comment]
Which name for _tau_ did we decide on eventually?

**Comment by ambarb** [comment]
so a quick literature/internet search produced some information.

I thinks "delay" is the experimentalists' term because they had to add an electronic delay to the data collection circuit back in the 50s.  From a statistics point of view, the word "lag" is used.  I think both are technically correct.  I know the APS really likes delay so maybe we can go with `delay_step` but include in the description for this:

"delay (or lag) is the quantized difference so that the "step" between 2 frames is 1 (or step = dt = 1 frame)."

**Comment by prjemian** [comment]
field name:  `ad_object.cam.acquire_period.pvname`  I believe AcquirePeriod_RBV

"step" still seems like jargon, so perhaps adding _time difference_ to the description, as in:

"delay (or lag) is the quantized difference so that the time difference ("step") between 2 frames is 1 (or step = dt = 1 frame).

**Comment by prjemian** [comment]
confirming the PV name with area detector `ad:` from the bash shell command line:

```sh
(base) prjemian@zap:~/Documents/build$ caget ad:cam1:AcquirePeriod
ad:cam1:AcquirePeriod          0.005
(base) prjemian@zap:~/Documents/build$ caget ad:cam1:AcquirePeriod_RBV
ad:cam1:AcquirePeriod_RBV      0.005
```

and from the bluesky IPython shell:

```python
In [1]: adsimdet.cam.acquire_period.pvname
Out[1]: 'ad:cam1:AcquirePeriod_RBV'
```

**Comment by prjemian** [comment]
But you were asking for the field name we us in NXxpcs?  NeXus has only one such use, in NXsource as `period`.  Our use is different.  Suggest adding `acquire_period` t _our use of_ NXdetector.

**Comment by ambarb** [comment]
refreshing our memory, we know that we decided:

tau --> delay_difference
