### ISSUE TITLE
why is the two-time subentry not under data sub entry

### ISSUE THREAD

**Issue by ambarb** [lightsources/BES-XPCS-Pilot#48]
- @JulReinhardt says creater changes will be straightforward
- We should understand from @prjemian if there was a reason to keep them separate.

**Comment by prjemian** [comment]
As best I understand it, the twotime correlation is a separate result.  Placing that result in a separate `NXdata` group allows a default plot configured for twotime results, separate from the default plot of g2 results.  (The point of `NXdata` groups, despite the _data_ name, is to make a plot of data).

**Comment by JulReinhardt** [comment]
So we keep it separate with an own data group like we have it here: 
![image](https://user-images.githubusercontent.com/32627728/127564761-e18af803-3ef9-4745-9894-4e47ac51f902.png)
Please confirm @prjemian

**Comment by prjemian** [comment]
@JulReinhardt - I agree.

**Comment by ambarb** [comment]
ok.  closing this since no changes are need to address this specific issue.

though, I am not sure it should be required.  I think that this is a seperate issue though.
