### ISSUE TITLE
remove `mask` from entry/xpcs/masks/mask

### ISSUE THREAD

**Issue by ambarb** [lightsources/BES-XPCS-Pilot#53]
need to confirm

![image](https://user-images.githubusercontent.com/13630233/124302257-f4626600-db2e-11eb-9a20-a0d7d19901ed.png)

**Comment by ambarb** [comment]
seems #57 page 13 says "bin" --> "roi"

The reader's digest justification is python library uses roi in a more general context and not in the way that certain AreaDetector plugins work.

**Comment by ambarb** [comment]
from discussion with @prjemian , this `mask` was added with @ronpandolfi in early days of the project.  We think this is redundant and we verify that it can be deleted. 

@JulReinhardt will verify that it is gone and we can move this to complete when that happens.

**Comment by prjemian** [comment]
Waiting for PR #52 to merge.
