### ISSUE TITLE
generate a list of required that should be optional and vice versa

### ISSUE THREAD

**Issue by ambarb** [lightsources/BES-XPCS-Pilot#60]

**Comment by ambarb** [comment]
not required using Pete's NXxpcs mock webpage

If required means teh field is required, but the field doesn't require a value, then maybe this is not essential.

- [ ]  anything associated with 2-time otr `twotime`.  it isn't always calculated depending on choices of user doing the experiment.
- [ ] `g2_errors` 
- [ ] `dphilist`, `sqmap`, `sqlist`. --> dynamic_phi_list , static_roi_map , static_q_list
- [ ] `sample\position_x` and`_y` and `_z` .  depending on instrument and experimental setup these details may be irrelevant
-

**Comment by ambarb** [comment]
@prjemian I am happy to contribute to PR if we need to addres it.  Can you answer my question about the meaning of "required"

**Comment by prjemian** [comment]
_required_ means a value must be provided

We can make such fields optional if a value is not always expected to be available.  (not truly _required_)

**Comment by ambarb** [comment]
we all believe that we are done (with pushes)

if there are more, they will come up in our XPCS community review.
